[tasks.objcopy]
command = "cargo"
args= [
    "objcopy",
    "--release",
    "--",
    "-O", "binary",
    "target/thumbv7em-none-eabihf/release/g4.bin"
]
[tasks.dfu]
command = "dfu-util"
args = [
    "-d", "0483:df11",
    "-a", "0",
    "-s", "0x08000000:leave",
    "-D", "target/thumbv7em-none-eabihf/release/g4.bin"
]
dependencies = ["objcopy"]